export const messageData = [
    {
        id: "u1",
        username: "john_doe",
        name: "John Doe",
        user: {
            id: "u1",
            username: "john_doe",
            name: "John Doe",
            profilePic: "https://randomuser.me/api/portraits/men/32.jpg",
        },
        profilePic: "https://randomuser.me/api/portraits/men/32.jpg",
        isOnline: true,
        presence: "Active Now",
        isVerified: true,
        hasStory: true,
        unreadCount: 0,
    },
    {
        id: "u2",
        username: "emma_w",
        name: "Emma Watson",
        user: {
            id: "u2",
            username: "emma_w",
            name: "Emma Watson",
            profilePic: "https://randomuser.me/api/portraits/women/44.jpg",
        },
        profilePic: "https://randomuser.me/api/portraits/women/44.jpg",
        isOnline: true,
        presence: "typing",
        hasStory: true,
        unreadCount: 2,
    },
    {
        id: "u3",
        username: "michael_23",
        name: "Michael",
        user: {
            id: "u3",
            username: "michael_23",
            name: "Michael",
            profilePic: "https://randomuser.me/api/portraits/men/67.jpg",
        },
        profilePic: "https://randomuser.me/api/portraits/men/67.jpg",
        isOnline: true,
        presence: "3 new messages",
        hasStory: false,
        unreadCount: 1,
    },
    {
        id: "u4",
        username: "sarah_s",
        name: "Sarah S",
        user: {
            id: "u4",
            username: "sarah_s",
            name: "Sarah S",
            profilePic: "https://randomuser.me/api/portraits/women/12.jpg",
        },
        profilePic: "https://randomuser.me/api/portraits/women/12.jpg",
        isOnline: true,
        presence: "Active Now",
        isVerified: false,
        hasStory: true,
    },
    {
        id: "u5",
        username: "kevin_m",
        name: "Kevin",
        user: {
            id: "u5",
            username: "kevin_m",
            name: "Kevin",
            profilePic: "https://randomuser.me/api/portraits/men/50.jpg",
        },
        profilePic: "https://randomuser.me/api/portraits/men/50.jpg",
        isOnline: true,
        presence: "1 new messages",
        hasStory: false,
    },
    {
        id: "u6",
        username: "olivia_r",
        name: "Olivia",
        user: {
            id: "u6",
            username: "olivia_r",
            name: "Olivia",
            profilePic: "https://randomuser.me/api/portraits/women/65.jpg",
        },
        profilePic: "https://randomuser.me/api/portraits/women/65.jpg",
        isOnline: true,
        presence: "Active Now",
        hasStory: true,
    },
    {
        id: "u7",
        username: "aarav_p",
        name: "Aarav",
        user: {
            id: "u7",
            username: "aarav_p",
            name: "Aarav",
            profilePic: "https://randomuser.me/api/portraits/men/11.jpg",
        },
        profilePic: "https://randomuser.me/api/portraits/men/11.jpg",
        isOnline: false,
        presence: "Recently Active",
        lastActiveMins: 5,
        hasStory: true,
    },
    {
        id: "u8",
        username: "mia_chan",
        name: "Mia",
        user: {
            id: "u8",
            username: "mia_chan",
            name: "Mia",
            profilePic: "https://randomuser.me/api/portraits/women/14.jpg",
        },
        profilePic: "https://randomuser.me/api/portraits/women/14.jpg",
        isOnline: false,
        presence: "Recently Active",
        lastActiveMins: 9,
        hasStory: false,
    },
    {
        id: "u9",
        username: "ryan_g",
        name: "Ryan",
        user: {
            id: "u9",
            username: "ryan_g",
            name: "Ryan",
            profilePic: "https://randomuser.me/api/portraits/men/23.jpg",
        },
        profilePic: "https://randomuser.me/api/portraits/men/23.jpg",
        isOnline: false,
        presence: "Recently Active",
        lastActiveMins: 14,
        hasStory: true,
    },
    {
        id: "u10",
        username: "zoe_99",
        name: "Zoe",
        user: {
            id: "u10",
            username: "zoe_99",
            name: "Zoe",
            profilePic: "https://randomuser.me/api/portraits/women/45.jpg",
        },
        profilePic: "https://randomuser.me/api/portraits/women/45.jpg",
        isOnline: false,
        presence: "offline",
        lastActiveMins: 120, // 2h ago
        hasStory: false,
    },
    {
        id: "u11",
        username: "daniel_s",
        name: "Daniel",
        user: {
            id: "u11",
            username: "daniel_s",
            name: "Daniel",
            profilePic: "https://randomuser.me/api/portraits/men/77.jpg",
        },
        profilePic: "https://randomuser.me/api/portraits/men/77.jpg",
        isOnline: true,
        presence: "Active Now",
        hasStory: true,
    },
    {
        id: "u12",
        username: "clara_b",
        name: "Clara",
        user: {
            id: "u12",
            username: "clara_b",
            name: "Clara",
            profilePic: "https://randomuser.me/api/portraits/women/19.jpg",
        },
        profilePic: "https://randomuser.me/api/portraits/women/19.jpg",
        isOnline: false,
        presence: "Recently Active",
        lastActiveMins: 2,
        hasStory: true,
        unreadCount: 3,
    },
    {
        id: "u13",
        username: "leo_x",
        name: "Leo",
        user: {
            id: "u13",
            username: "leo_x",
            name: "Leo",
            profilePic: "https://randomuser.me/api/portraits/men/19.jpg",
        },
        profilePic: "https://randomuser.me/api/portraits/men/19.jpg",
        isOnline: true,
        presence: "typing",
        hasStory: false,
    },
    {
        id: "u14",
        username: "natalie_y",
        name: "Natalie",
        user: {
            id: "u14",
            username: "natalie_y",
            name: "Natalie",
            profilePic: "https://randomuser.me/api/portraits/women/53.jpg",
        },
        profilePic: "https://randomuser.me/api/portraits/women/53.jpg",
        isOnline: false,
        presence: "offline",
        lastActiveMins: 400, // ~6h 40m
        hasStory: false,
    },
    {
        id: "u15",
        username: "sanjay_k",
        name: "Sanjay",
        user: {
            id: "u15",
            username: "sanjay_k",
            name: "Sanjay",
            profilePic: "https://randomuser.me/api/portraits/men/3.jpg",
        },
        profilePic: "https://randomuser.me/api/portraits/men/3.jpg",
        isOnline: true,
        presence: "Active Now",
        hasStory: true,
    },
    {
        id: "u16",
        username: "priya_v",
        name: "Priya",
        user: {
            id: "u16",
            username: "priya_v",
            name: "Priya",
            profilePic: "https://randomuser.me/api/portraits/women/8.jpg",
        },
        profilePic: "https://randomuser.me/api/portraits/women/8.jpg",
        isOnline: false,
        presence: "Recently Active",
        lastActiveMins: 28,
        hasStory: true,
    },
    {
        id: "u17",
        username: "dev_r",
        name: "Dev",
        user: {
            id: "u17",
            username: "dev_r",
            name: "Dev",
            profilePic: "https://randomuser.me/api/portraits/men/84.jpg",
        },
        profilePic: "https://randomuser.me/api/portraits/men/84.jpg",
        isOnline: false,
        presence: "offline",
        lastActiveMins: 980, // ~16h
        hasStory: false,
    },
    {
        id: "u18",
        username: "tanya_m",
        name: "Tanya",
        user: {
            id: "u18",
            username: "tanya_m",
            name: "Tanya",
            profilePic: "https://randomuser.me/api/portraits/women/21.jpg",
        },
        profilePic: "https://randomuser.me/api/portraits/women/21.jpg",
        isOnline: true,
        presence: "Active Now",
        hasStory: true,
        unreadCount: 1,
    },
    {
        id: "u19",
        username: "omar_z",
        name: "Omar",
        user: {
            id: "u19",
            username: "omar_z",
            name: "Omar",
            profilePic: "https://randomuser.me/api/portraits/men/56.jpg",
        },
        profilePic: "https://randomuser.me/api/portraits/men/56.jpg",
        isOnline: false,
        presence: "Recently Active",
        lastActiveMins: 7,
        hasStory: false,
    },
    {
        id: "u20",
        username: "lisa_k",
        name: "Lisa",
        user: {
            id: "u20",
            username: "lisa_k",
            name: "Lisa",
            profilePic: "https://randomuser.me/api/portraits/women/30.jpg",
        },
        profilePic: "https://randomuser.me/api/portraits/women/30.jpg",
        isOnline: true,
        presence: "typing",
        hasStory: true,
    },
];
