export const posts = [
    {
        id: '1',
        type: 'image',
        user: {
            id: '1',
            name: 'Wanderlust Sam',
            username: 'wanderlust_sam',
            profilePic: 'https://randomuser.me/api/portraits/men/32.jpg',
        },
        mediaUrl: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=1080',
        aspectRatio: 1, // square (1080x1080)
        caption: 'Chasing sunsets 🌅 #wanderlust #wanderlust #wanderlust #wanderlust #wanderlust #wanderlust #wanderlust #wanderlust ',
        isLiked: true,
        likes: 32,
        comments: [
            { id: 'c1', username: 'travel_buddy', text: 'This is stunning 😍' },
        ],
        sharedCount: 6,
        timeAgo: '2 hours ago',
    },
    {
        id: '2',
        type: 'image',
        user: {
            id: '2',
            name: 'Foodie Life',
            username: 'foodie_life',
            profilePic: 'https://randomuser.me/api/portraits/women/21.jpg',
        },
        mediaUrl: 'https://images.unsplash.com/photo-1551782450-a2132b4ba21d?w=1080',
        aspectRatio: 4 / 5, // portrait (1080x1350)
        caption: 'Sunday brunch is my happy place 🥞🍓',
        isLiked: false,
        likes: 689,
        comments: [
            { id: 'c2', username: 'chef_mom', text: 'I need this right now 🤤' },
            { id: 'c2', username: 'chef_mom', text: 'I need this right now 🤤' },
        ],
        sharedCount: 1,
        timeAgo: '5 hours ago',
    },
    {
        id: '3',
        type: 'image',
        user: {
            id: '3',
            name: 'Urban Clicks',
            username: 'urban_clicks',
            profilePic: 'https://randomuser.me/api/portraits/men/12.jpg',
        },
        mediaUrl: 'https://images.unsplash.com/photo-1501594907352-04cda38ebc29?w=1080',
        aspectRatio: 1.91, // landscape (1080x608)
        caption: 'City lights never sleep 🌃✨',
        isLiked: false,
        likes: 320,
        comments: [
            { id: 'c3', username: 'night_owl', text: 'Insane vibes 🔥' },
            { id: 'c3', username: 'night_owl', text: 'Insane vibes 🔥' },
            { id: 'c3', username: 'night_owl', text: 'Insane vibes 🔥' },
            { id: 'c3', username: 'night_owl', text: 'Insane vibes 🔥' },
        ],
        sharedCount: 2,
        timeAgo: '1 day ago',
    },
    {
        id: '4',
        type: 'image',
        user: {
            id: '4',
            name: 'Wanderlust Sam',
            username: 'wanderlust_sam',
            profilePic: 'https://randomuser.me/api/portraits/men/37.jpg',
        },
        mediaUrl: 'https://picsum.photos/1080/1080?random=1',
        aspectRatio: 4 / 5, // square (1080x1080)
        caption: 'Chasing sunsets 🌅 #wanderlust',
        isLiked: false,
        likes: 3,
        comments: [
            { id: 'c1', username: 'travel_buddy', text: 'This is stunning 😍' },
        ],
        timeAgo: '9 hours ago',
    },
    {
        id: '5',
        type: 'image',
        user: {
            id: '5',
            name: 'Nature Life',
            username: 'nature_life',
            profilePic: 'https://randomuser.me/api/portraits/women/20.jpg',
        },
        mediaUrl: 'https://picsum.photos/1080/1080?random=2',
        aspectRatio: 1, // portrait (1080x1350)
        caption: 'Sunday brunch is my happy place 🥞🍓',
        isLiked: false,
        likes: 589,
        comments: [
            { id: 'c2', username: 'chef_mom', text: 'wow 🤤' },
            { id: 'c2', username: 'chef_mom', text: 'Very nice view 🤤' },
        ],
        sharedCount: 32,
        timeAgo: '4 hours ago',
    },
    {
        id: '6',
        type: 'image',
        user: {
            id: '6',
            name: 'Urban Clicks',
            username: 'urban_clicks',
            profilePic: 'https://randomuser.me/api/portraits/men/12.jpg',
        },
        mediaUrl: 'https://picsum.photos/1080/1080?random=3',
        aspectRatio: 1, // landscape (1080x608)
        caption: 'City lights never sleep 🌃✨',
        isLiked: false,
        likes: 310,
        comments: [
            { id: 'c3', username: 'night_owl', text: 'Insane vibes 🔥' },
            { id: 'c3', username: 'night_owl', text: 'Insane vibes 🔥' },
            { id: 'c3', username: 'night_owl', text: 'Insane vibes 🔥' },
            { id: 'c3', username: 'night_owl', text: 'Insane vibes 🔥' },
        ],
        sharedCount: 32,
        timeAgo: '1 day ago',
    },
    {
        id: '7',
        type: 'image',
        user: {
            id: '7',
            name: 'Wanderlust Sam',
            username: 'wanderlust_sam',
            profilePic: 'https://randomuser.me/api/portraits/men/32.jpg',
        },
        mediaUrl: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=1080',
        aspectRatio: 1, // square (1080x1080)
        caption: 'Chasing sunsets 🌅 #wanderlust #wanderlust #wanderlust #wanderlust #wanderlust #wanderlust #wanderlust #wanderlust ',
        isLiked: true,
        likes: 32,
        comments: [
            { id: 'c1', username: 'travel_buddy', text: 'This is stunning 😍' },
        ],
        sharedCount: 6,
        timeAgo: '2 hours ago',
    },
    {
        id: '8',
        type: 'image',
        user: {
            id: '8',
            name: 'Foodie Life',
            username: 'foodie_life',
            profilePic: 'https://randomuser.me/api/portraits/women/21.jpg',
        },
        mediaUrl: 'https://images.unsplash.com/photo-1551782450-a2132b4ba21d?w=1080',
        aspectRatio: 4 / 5, // portrait (1080x1350)
        caption: 'Sunday brunch is my happy place 🥞🍓',
        isLiked: false,
        likes: 689,
        comments: [
            { id: 'c2', username: 'chef_mom', text: 'I need this right now 🤤' },
            { id: 'c2', username: 'chef_mom', text: 'I need this right now 🤤' },
        ],
        sharedCount: 1,
        timeAgo: '5 hours ago',
    },
    {
        id: '9',
        type: 'image',
        user: {
            id: '9',
            name: 'Urban Clicks',
            username: 'urban_clicks',
            profilePic: 'https://randomuser.me/api/portraits/men/12.jpg',
        },
        mediaUrl: 'https://images.unsplash.com/photo-1501594907352-04cda38ebc29?w=1080',
        aspectRatio: 1.91, // landscape (1080x608)
        caption: 'City lights never sleep 🌃✨',
        isLiked: false,
        likes: 320,
        comments: [
            { id: 'c3', username: 'night_owl', text: 'Insane vibes 🔥' },
            { id: 'c3', username: 'night_owl', text: 'Insane vibes 🔥' },
            { id: 'c3', username: 'night_owl', text: 'Insane vibes 🔥' },
            { id: 'c3', username: 'night_owl', text: 'Insane vibes 🔥' },
        ],
        sharedCount: 2,
        timeAgo: '1 day ago',
    },
    {
        id: '10',
        type: 'image',
        user: {
            id: '10',
            name: 'Wanderlust Sam',
            username: 'wanderlust_sam',
            profilePic: 'https://randomuser.me/api/portraits/men/37.jpg',
        },
        mediaUrl: 'https://picsum.photos/1080/1080?random=1',
        aspectRatio: 4 / 5, // square (1080x1080)
        caption: 'Chasing sunsets 🌅 #wanderlust',
        isLiked: false,
        likes: 3,
        comments: [
            { id: 'c1', username: 'travel_buddy', text: 'This is stunning 😍' },
        ],
        timeAgo: '9 hours ago',
    },
    {
        id: '11',
        type: 'image',
        user: {
            id: '11',
            name: 'Nature Life',
            username: 'nature_life',
            profilePic: 'https://randomuser.me/api/portraits/women/20.jpg',
        },
        mediaUrl: 'https://picsum.photos/1080/1080?random=2',
        aspectRatio: 1, // portrait (1080x1350)
        caption: 'Sunday brunch is my happy place 🥞🍓',
        isLiked: false,
        likes: 589,
        comments: [
            { id: 'c2', username: 'chef_mom', text: 'wow 🤤' },
            { id: 'c2', username: 'chef_mom', text: 'Very nice view 🤤' },
        ],
        sharedCount: 32,
        timeAgo: '4 hours ago',
    },
    {
        id: '12',
        type: 'image',
        user: {
            id: '12',
            name: 'Urban Clicks',
            username: 'urban_clicks',
            profilePic: 'https://randomuser.me/api/portraits/men/12.jpg',
        },
        mediaUrl: 'https://picsum.photos/1080/1080?random=3',
        aspectRatio: 1, // landscape (1080x608)
        caption: 'City lights never sleep 🌃✨',
        isLiked: false,
        likes: 310,
        comments: [
            { id: 'c3', username: 'night_owl', text: 'Insane vibes 🔥' },
            { id: 'c3', username: 'night_owl', text: 'Insane vibes 🔥' },
            { id: 'c3', username: 'night_owl', text: 'Insane vibes 🔥' },
            { id: 'c3', username: 'night_owl', text: 'Insane vibes 🔥' },
        ],
        sharedCount: 32,
        timeAgo: '1 day ago',
    },
    {
        id: '13',
        type: 'image',
        user: {
            id: '7',
            name: 'Wanderlust Sam',
            username: 'wanderlust_sam',
            profilePic: 'https://randomuser.me/api/portraits/men/32.jpg',
        },
        mediaUrl: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=1080',
        aspectRatio: 1, // square (1080x1080)
        caption: 'Chasing sunsets 🌅 #wanderlust #wanderlust #wanderlust #wanderlust #wanderlust #wanderlust #wanderlust #wanderlust ',
        isLiked: true,
        likes: 32,
        comments: [
            { id: 'c1', username: 'travel_buddy', text: 'This is stunning 😍' },
        ],
        sharedCount: 6,
        timeAgo: '2 hours ago',
    },
    {
        id: '14',
        type: 'image',
        user: {
            id: '8',
            name: 'Foodie Life',
            username: 'foodie_life',
            profilePic: 'https://randomuser.me/api/portraits/women/21.jpg',
        },
        mediaUrl: 'https://images.unsplash.com/photo-1551782450-a2132b4ba21d?w=1080',
        aspectRatio: 4 / 5, // portrait (1080x1350)
        caption: 'Sunday brunch is my happy place 🥞🍓',
        isLiked: false,
        likes: 689,
        comments: [
            { id: 'c2', username: 'chef_mom', text: 'I need this right now 🤤' },
            { id: 'c2', username: 'chef_mom', text: 'I need this right now 🤤' },
        ],
        sharedCount: 1,
        timeAgo: '5 hours ago',
    },
    {
        id: '15',
        type: 'image',
        user: {
            id: '9',
            name: 'Urban Clicks',
            username: 'urban_clicks',
            profilePic: 'https://randomuser.me/api/portraits/men/12.jpg',
        },
        mediaUrl: 'https://images.unsplash.com/photo-1501594907352-04cda38ebc29?w=1080',
        aspectRatio: 1.91, // landscape (1080x608)
        caption: 'City lights never sleep 🌃✨',
        isLiked: false,
        likes: 320,
        comments: [
            { id: 'c3', username: 'night_owl', text: 'Insane vibes 🔥' },
            { id: 'c3', username: 'night_owl', text: 'Insane vibes 🔥' },
            { id: 'c3', username: 'night_owl', text: 'Insane vibes 🔥' },
            { id: 'c3', username: 'night_owl', text: 'Insane vibes 🔥' },
        ],
        sharedCount: 2,
        timeAgo: '1 day ago',
    },
    {
        id: '16',
        type: 'image',
        user: {
            id: '10',
            name: 'Wanderlust Sam',
            username: 'wanderlust_sam',
            profilePic: 'https://randomuser.me/api/portraits/men/37.jpg',
        },
        mediaUrl: 'https://picsum.photos/1080/1080?random=1',
        aspectRatio: 4 / 5, // square (1080x1080)
        caption: 'Chasing sunsets 🌅 #wanderlust',
        isLiked: false,
        likes: 3,
        comments: [
            { id: 'c1', username: 'travel_buddy', text: 'This is stunning 😍' },
        ],
        timeAgo: '9 hours ago',
    },
    {
        id: '17',
        type: 'image',
        user: {
            id: '11',
            name: 'Nature Life',
            username: 'nature_life',
            profilePic: 'https://randomuser.me/api/portraits/women/20.jpg',
        },
        mediaUrl: 'https://picsum.photos/1080/1080?random=2',
        aspectRatio: 1, // portrait (1080x1350)
        caption: 'Sunday brunch is my happy place 🥞🍓',
        isLiked: false,
        likes: 589,
        comments: [
            { id: 'c2', username: 'chef_mom', text: 'wow 🤤' },
            { id: 'c2', username: 'chef_mom', text: 'Very nice view 🤤' },
        ],
        sharedCount: 32,
        timeAgo: '4 hours ago',
    },
    {
        id: '18',
        type: 'image',
        user: {
            id: '12',
            name: 'Urban Clicks',
            username: 'urban_clicks',
            profilePic: 'https://randomuser.me/api/portraits/men/12.jpg',
        },
        mediaUrl: 'https://picsum.photos/1080/1080?random=3',
        aspectRatio: 1, // landscape (1080x608)
        caption: 'City lights never sleep 🌃✨',
        isLiked: false,
        likes: 310,
        comments: [
            { id: 'c3', username: 'night_owl', text: 'Insane vibes 🔥' },
            { id: 'c3', username: 'night_owl', text: 'Insane vibes 🔥' },
            { id: 'c3', username: 'night_owl', text: 'Insane vibes 🔥' },
            { id: 'c3', username: 'night_owl', text: 'Insane vibes 🔥' },
        ],
        sharedCount: 32,
        timeAgo: '1 day ago',
    },
];
