export const reelsData = [
    {
        id: '1',
        user: {
            name: 'good Morning',
            username: 'good_morning',
            profilePic: 'https://randomuser.me/api/portraits/men/32.jpg',
        },
        videoUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4',
        caption: 'Exploring the beautiful streets of Italy 🇮🇹✨ #TravelVibes #Italy',
        music: {
            title: 'Levitating',
            artist: 'Dua Lipa',
        },
        aspectRatio: 4 / 5,
        likes: 12999,
        comments: 540,
        reposts: 20,
        shareCount: 10,
        isLiked: false,
        followProfilePic: [
            'https://randomuser.me/api/portraits/women/18.jpg',
            'https://randomuser.me/api/portraits/women/19.jpg',
            'https://randomuser.me/api/portraits/women/20.jpg',
            'https://randomuser.me/api/portraits/women/21.jpg',
            'https://randomuser.me/api/portraits/women/22.jpg',
            'https://randomuser.me/api/portraits/women/23.jpg',
            'https://randomuser.me/api/portraits/women/24.jpg',
        ],
        timeAgo: '2h ago',
    },
    {
        id: '2',
        user: {
            name: 'fitness Guru',
            username: 'fitness_guru',
            profilePic: 'https://randomuser.me/api/portraits/women/21.jpg',
        },
        videoUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
        caption: 'No excuses, just results 💪🔥 #WorkoutMotivation #Motivation #Workout',
        music: {
            title: 'Eye of the Tiger',
            artist: 'Survivor',
        },
        aspectRatio: 4 / 5,
        likes: 8900,
        comments: 320,
        reposts: 5,
        shareCount: 6,
        isLiked: true,
        followProfilePic: [
            'https://randomuser.me/api/portraits/women/18.jpg',
            'https://randomuser.me/api/portraits/women/19.jpg',
            'https://randomuser.me/api/portraits/women/20.jpg',
            'https://randomuser.me/api/portraits/women/21.jpg',
            'https://randomuser.me/api/portraits/women/22.jpg',
            'https://randomuser.me/api/portraits/women/23.jpg',
            'https://randomuser.me/api/portraits/women/24.jpg',
        ],
        timeAgo: '5h ago',
    },
    {
        id: '3',
        user: {
            name: 'chef Julia',
            username: 'chef_julia_3',
            profilePic: 'https://randomuser.me/api/portraits/men/12.jpg',
        },
        videoUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
        caption: 'Quick & easy pasta recipe 🍝✨ #FoodieLife',
        music: {
            title: 'Good Vibes',
            artist: 'Chris Janson',
        },
        aspectRatio: 4 / 5,
        likes: 408,
        comments: 280,
        reposts: 32,
        shareCount: 17,
        isLiked: false,
        followProfilePic: [
            'https://randomuser.me/api/portraits/women/18.jpg',
            'https://randomuser.me/api/portraits/women/19.jpg',
            'https://randomuser.me/api/portraits/women/20.jpg',
            'https://randomuser.me/api/portraits/women/21.jpg',
            'https://randomuser.me/api/portraits/women/22.jpg',
            'https://randomuser.me/api/portraits/women/23.jpg',
            'https://randomuser.me/api/portraits/women/24.jpg',
        ],
        timeAgo: '1d ago',
    },
    {
        id: '4',
        user: {
            name: 'chef Julia',
            username: 'chef_julia',
            profilePic: 'https://randomuser.me/api/portraits/women/45.jpg',
        },
        videoUrl: 'https://sample-videos.com/video321/mp4/720/big_buck_bunny_720p_5mb.mp4',
        caption: 'Quick & easy pasta recipe 🍝✨ #FoodieLife',
        music: {
            title: 'Good Vibes',
            artist: 'Chris Janson',
        },
        aspectRatio: 4 / 5,
        likes: 420,
        comments: 18,
        reposts: 22,
        shareCount: 31,
        isLiked: false,
        followProfilePic: [
            'https://randomuser.me/api/portraits/women/18.jpg',
            'https://randomuser.me/api/portraits/women/19.jpg',
            'https://randomuser.me/api/portraits/women/20.jpg',
            'https://randomuser.me/api/portraits/women/21.jpg',
            'https://randomuser.me/api/portraits/women/22.jpg',
            'https://randomuser.me/api/portraits/women/23.jpg',
            'https://randomuser.me/api/portraits/women/24.jpg',
        ],
        timeAgo: '1d ago',
    },
    {
        id: '5',
        user: {
            name: 'chef Julia',
            username: 'chef_julia_1',
            profilePic: 'https://randomuser.me/api/portraits/women/18.jpg',
        },
        videoUrl: 'https://sample-videos.com/video321/mp4/720/big_buck_bunny_720p_5mb.mp4',
        caption: 'Quick & easy pasta recipe 🍝✨ #FoodieLife',
        music: {
            title: 'Good Vibes',
            artist: 'Chris Janson',
        },
        aspectRatio: 4 / 5,
        likes: 400,
        comments: 80,
        reposts: 12,
        shareCount: 11,
        isLiked: false,
        followProfilePic: [
            'https://randomuser.me/api/portraits/women/18.jpg',
            'https://randomuser.me/api/portraits/women/19.jpg',
            'https://randomuser.me/api/portraits/women/20.jpg',
            'https://randomuser.me/api/portraits/women/21.jpg',
            'https://randomuser.me/api/portraits/women/22.jpg',
            'https://randomuser.me/api/portraits/women/23.jpg',
            'https://randomuser.me/api/portraits/women/24.jpg',
        ],
        timeAgo: '1d ago',
    },
    {
        id: '6',
        user: {
            name: 'chef Julia',
            username: 'chef_julia_2',
            profilePic: 'https://randomuser.me/api/portraits/men/19.jpg',
        },
        videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4',
        caption: 'Quick & easy pasta recipe 🍝✨ #FoodieLife',
        music: {
            title: 'Good Vibes',
            artist: 'Chris Janson',
        },
        aspectRatio: 4 / 5,
        likes: 1000000,
        comments: 2999,
        reposts: 2,
        shareCount: 1,
        isLiked: true,
        followProfilePic: [
            'https://randomuser.me/api/portraits/women/18.jpg',
            'https://randomuser.me/api/portraits/women/19.jpg',
            'https://randomuser.me/api/portraits/women/20.jpg',
            'https://randomuser.me/api/portraits/women/21.jpg',
            'https://randomuser.me/api/portraits/women/22.jpg',
            'https://randomuser.me/api/portraits/women/23.jpg',
            'https://randomuser.me/api/portraits/women/24.jpg',
        ],
        timeAgo: '1d ago',
    },
];
