export const usersData = [
    {
        id: '1',
        name: 'Divy Vasani',
        username: 'divy_vasani',
        profilePic: 'https://randomuser.me/api/portraits/men/1.jpg',
        pronouns: '',
        bio: 'I ❤️ My Self',
        gender: 'male',
        music: 'Good Vibes',
        followers: 100,
        followedBy: [
            'kirtan123',
            'sahil_123',
            'jay_vanani',
            'vraj_vasani',
            'harsh',
            'himanshu',
        ],
        following: 20,
        posts: 30,
    },
    {
        id: '2',
        name: 'Kirtan',
        username: 'kirtan123',
        profilePic: 'https://randomuser.me/api/portraits/men/2.jpg',
        pronouns: '',
        bio: 'I ❤️ My Self',
        gender: 'male',
        music: 'Good Vibes',
        followers: 100,
        followedBy: [
            'kirtan123',
            'sahil_123',
            'jay_vanani',
            'vraj_vasani',
            'harsh',
            'himanshu',
        ],
        following: 20,
        posts: 30,
    },
    {
        id: '3',
        name: 'sahil',
        username: 'sahil_123',
        profilePic: 'https://randomuser.me/api/portraits/men/3.jpg',
        pronouns: '',
        bio: 'I ❤️ My Self',
        gender: 'male',
        music: 'Good Vibes',
        followers: 100,
        followedBy: [
            'kirtan123',
            'sahil_123',
            'jay_vanani',
            'vraj_vasani',
            'harsh',
            'himanshu',
        ],
        following: 20,
        posts: 30,
    },
    {
        id: '4',
        name: 'jay',
        username: 'jay_vanani',
        profilePic: 'https://randomuser.me/api/portraits/men/4.jpg',
        pronouns: '',
        bio: 'I ❤️ My Self',
        gender: 'male',
        music: 'Good Vibes',
        followers: 100,
        followedBy: [
            'kirtan123',
            'sahil_123',
            'jay_vanani',
            'vraj_vasani',
            'harsh',
            'himanshu',
        ],
        following: 20,
        posts: 30,
    },
    {
        id: '5',
        name: 'vraj vasani',
        username: 'vraj_vasani',
        profilePic: 'https://randomuser.me/api/portraits/men/5.jpg',
        pronouns: '',
        bio: 'I ❤️ My Self',
        gender: 'male',
        music: 'Good Vibes',
        followers: 100,
        followedBy: [
            'kirtan123',
            'sahil_123',
            'jay_vanani',
            'vraj_vasani',
            'harsh',
            'himanshu',
        ],
        following: 20,
        posts: 30,
    },
    {
        id: '6',
        name: 'harsh',
        username: 'h_k',
        profilePic: 'https://randomuser.me/api/portraits/men/6.jpg',
        pronouns: '',
        bio: 'I ❤️ My Self',
        gender: 'male',
        music: 'Good Vibes',
        followers: 100,
        followedBy: [
            'kirtan123',
            'sahil_123',
            'jay_vanani',
            'vraj_vasani',
            'harsh',
            'himanshu',
        ],
        following: 20,
        posts: 30,
    },
    {
        id: '7',
        name: 'himanshu',
        username: 'himanshu_231',
        profilePic: 'https://randomuser.me/api/portraits/men/7.jpg',
        pronouns: '',
        bio: 'I ❤️ My Self',
        gender: 'male',
        music: 'Good Vibes',
        followers: 100,
        followedBy: [
            'kirtan123',
            'sahil_123',
            'jay_vanani',
            'vraj_vasani',
            'harsh',
            'himanshu',
        ],
        following: 20,
        posts: 30,
    },
    {
        id: '8',
        name: 'dhruvisha',
        username: 'dhruvisha_231',
        profilePic: 'https://randomuser.me/api/portraits/women/1.jpg',
        pronouns: '',
        bio: 'I ❤️ My Self',
        gender: 'female',
        music: 'Good Vibes',
        followers: 100,
        followedBy: [
            'kirtan123',
            'sahil_123',
            'jay_vanani',
            'vraj_vasani',
            'harsh',
            'himanshu',
        ],
        following: 20,
        posts: 30,
    },
    {
        id: '9',
        name: 'tulsi',
        username: 'tulsi_21',
        profilePic: 'https://randomuser.me/api/portraits/women/2.jpg',
        pronouns: '',
        bio: 'I ❤️ My Self',
        gender: 'female',
        music: 'Good Vibes',
        followers: 100,
        followedBy: [
            'kirtan123',
            'sahil_123',
            'jay_vanani',
            'vraj_vasani',
            'harsh',
            'himanshu',
        ],
        following: 20,
        posts: 30,
    },
    {
        id: '10',
        name: 'avani',
        username: 'avani_21',
        profilePic: 'https://randomuser.me/api/portraits/women/3.jpg',
        pronouns: '',
        bio: 'I ❤️ My Self',
        gender: 'female',
        music: 'Good Vibes',
        followers: 100,
        followedBy: [
            'kirtan123',
            'sahil_123',
            'jay_vanani',
            'vraj_vasani',
            'harsh',
            'himanshu',
        ],
        following: 20,
        posts: 30,
    },
    {
        id: '11',
        name: 'priyanka',
        username: 'priyanka_210',
        profilePic: 'https://randomuser.me/api/portraits/women/4.jpg',
        pronouns: '',
        bio: 'I ❤️ My Self',
        gender: 'female',
        music: 'Good Vibes',
        followers: 100,
        followedBy: [
            'kirtan123',
            'sahil_123',
            'jay_vanani',
            'vraj_vasani',
            'harsh',
            'himanshu',
        ],
        following: 20,
        posts: 30,
    },
    {
        id: '12',
        name: 'virendra',
        username: 'virendra_210',
        profilePic: 'https://randomuser.me/api/portraits/men/8.jpg',
        pronouns: '',
        bio: 'I ❤️ My Self',
        gender: 'male',
        music: 'Good Vibes',
        followers: 100,
        followedBy: [
            'kirtan123',
            'sahil_123',
            'jay_vanani',
            'vraj_vasani',
            'harsh',
            'himanshu',
        ],
        following: 20,
        posts: 30,
    },
    {
        id: '13',
        name: 'keyur',
        username: 'keyur_210',
        profilePic: 'https://randomuser.me/api/portraits/men/9.jpg',
        pronouns: '',
        bio: 'I ❤️ My Self',
        gender: 'male',
        music: 'Good Vibes',
        followers: 100,
        followedBy: [
            'kirtan123',
            'sahil_123',
            'jay_vanani',
            'vraj_vasani',
            'harsh',
            'himanshu',
        ],
        following: 20,
        posts: 30,
    },
]